# 数据操作
## 入门

n维数组，也称为张量。在深度学习框架中，张量类（torch和tensorflow中都为tensor）与numpy的ndarray都类似。但又有所不同，numpy仅支持cpu计算，其次，张量类支持自动微分。

In [1]:
import torch

张量表示一个由数值组成的数组

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

知道张量中元素的总数，即形状的所有元素乘积，可以检查它的大小

In [3]:
x.shape

torch.Size([12])

改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数

In [4]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

有时，希望使用全0、全1、其他常量，或从特定分布中随机采样的数字来初始化矩阵，可以创建一个形状为（2，3，4）的张量，其中所有元素都设置为0

In [5]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

从某个特定的概率分布中随机采样来得到张量中每个元素的值

In [7]:
torch.randn(3,4)

tensor([[ 0.0486,  1.9536,  0.8097,  0.5185],
        [ 2.0401,  0.3591, -1.2623, -0.4383],
        [ 0.3868, -0.2946,  1.1877,  0.2535]])

## 运算符

In [8]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2  , 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [9]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

将张量连结在一起

In [10]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3],[1, 2, 3, 4],[4, 3, 2, 1]])
torch.cat((X, Y),dim=0),torch.cat((X, Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

对每个位置进行比较，相同则为true，否则则为false

In [11]:
X,Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [12]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [13]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [14]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

## 广播机制
1. 通过适当复制元素来扩展一个或者两个数组，以便在转化之后，两个张量具有相同的形状
2. 对生成的数组执行按元素操作

In [15]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [16]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片
[-1]选择最后一个元素，[1:3]选择第二个和第三个元素

In [17]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 节省内存

分配新的内存空间

In [19]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作：使用切片表示法将操作的结果分配给先前分配的数组，例如`Y[:] = <expression>`

In [20]:
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))

id(Z): 4420258368
id(Z): 4420258368


In [21]:
before = id(X)
X += Y
id(X) == before

True

## 转换为其他python对象

In [22]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [23]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)